/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dns.processor;

public class ProcessorApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ProcessorApplication().getGreeting());
    }
}
