/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dns.processor;

import org.junit.Test;
import static org.junit.Assert.*;

import org.dns.processor.ProcessorApplication;

public class ProcessorApplicationTest {
    @Test public void appHasAGreeting() {
        ProcessorApplication classUnderTest = new ProcessorApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
