/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dns.api;

import org.junit.Test;
import static org.junit.Assert.*;

import org.dns.api.ApiApplication;

public class ApiApplicationTest {
    @Test public void appHasAGreeting() {
        ApiApplication classUnderTest = new ApiApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
