/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dns.api;

public class ApiApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ApiApplication().getGreeting());
    }
}
